### ISSUE TITLE
Can't find dodgem after 0.2.11

### ISSUE THREAD

**Issue by JoffreySawyer** [jamiestraw/dodgem#4]
Starting dodgem gives a 'no such file or directory' error.

Or ok, I already fixed it by uninstalling and installing again.

To remove: 
`yarn global remove dodgem`

And add it again with

`yarn global add dodgem`

Quite basic but I'm guessing not everyone using this is that computer-savvy.

**Comment by jamiestraw** [comment]
Strange... Yarn doesn't seem to update the path to the binary when upgrading - I can see that the symlink is still pointing to `./index.js` after upgrading to `v0.2.11`.

I moved and renamed the binary to `/src/app.js` in this release.

Thanks for pointing this out @JoffreySawyer! 👍

I'm going to investigate this further to see if this is be a potential bug with @yarnpkg.

**Comment by jamiestraw** [comment]
After more investigation I'm quite sure that this is an issue with Yarn not updating changed binary symlinks when upgrading global packages.

I've opened a bug report with Yarn here: yarnpkg/yarn#4941.

**Comment by jamiestraw** [comment]
This has now been confirmed to be an issue with Yarn.

If anyone comes across this problem it can be resolved be re-installing dodgem:
```sh
yarn global remove dodgem
yarn global add dodgem
```

Thanks again @JoffreySawyer.
